var minsuData = {};
minsuData.minsuData00= {
    "data":{
		"pageStart":0,
		"pageSize":6,
		"count":6,
		"list":[{
			"creatAt":"空中花园南京路步行街店（粉色格子大床房）",
			"creatByFullName":"228",
			"price_icon":"￥",
            "sub_title1":"整套",
            "sub_title2":"可住2人|",
            "sub_title3":"人民广场/外滩",
			"sysId":1,
            "coverImg":"../img/indeximg/minsubig01.jpg",
            "Img":"../img/indeximg/minsusmall01.jpg",
			"status":2
			},{
			"creatAt":"【酒宿】靜安零距地鐵13/7/11-直通迪士尼秒玩市區•鄰法組界外灘南京路新天地•十分鐘上海站上戲•半小時虹橋機場火車站",
			"creatByFullName":"358",
			"price_icon":"￥",
            "sub_title1":"整套2居室",
            "sub_title2":"可住4人|",
            "sub_title3":"静安寺",
			"sysId":2,
            "coverImg":"../img/indeximg/minsubig02.jpg",
            "Img":"../img/indeximg/minsusmall02.jpg",
			"status":2
			},{
			"creatAt":"全宿|北外滩|恒升半岛|吴淞路|简约大床房|都市高层",
			"creatByFullName":"218",
			"price_icon":"￥",
            "sub_title1":"整套1居室",
            "sub_title2":"可住2人|",
            "sub_title3":"七浦路商业区",
			"sysId":3,
            "coverImg":"../img/indeximg/minsubig03.jpg",
            "Img":"../img/indeximg/minsusmall03.jpg",
			"status":2
			},{
			"creatAt":"《爱尚·逸家》繁华商圈，地铁口。私密情侣套房。",
			"creatByFullName":"258",
			"price_icon":"￥",
            "sub_title1":"整套1居室",
            "sub_title2":"可住2人|",
            "sub_title3":"四川北路",
			"sysId":4,
            "coverImg":"../img/indeximg/minsubig04.jpg",
            "Img":"../img/indeximg/minsusmall04.jpg",
			"status":2
			},{
			"creatAt":"上海野生动物园，迪斯尼乐园，新场古镇，海昌海洋公园，浦东机场，工商外国语学院，滴水湖",
			"creatByFullName":"238",
			"price_icon":"￥",
            "sub_title1":"整套2居室",
            "sub_title2":"可住4人|",
            "sub_title3":"南汇及野生动物园",
			"sysId":5,
            "coverImg":"../img/indeximg/minsubig05.jpg",
            "Img":"../img/indeximg/minsusmall05.jpg",
			"status":2
			},{
			"creatAt":"上海火车站旁步行500米北欧风LOFT公寓,小清新布置，近地铁1/3/4号线，地铁直达外滩，田子坊，大悦城，迪士尼。",
			"creatByFullName":"188",
			"price_icon":"￥",
            "sub_title1":"整套1居室",
            "sub_title2":"可住2人|",
            "sub_title3":"上海火车站",
			"sysId":6,
            "coverImg":"../img/indeximg/minsubig06.jpg",
            "Img":"../img/indeximg/minsusmall06.jpg",
			"status":2
			}
		]
	}
}